### ISSUE TITLE
Craftbook pipe and MC1421 IC need optimization

### ISSUE THREAD

**Issue by andris155** [EngineHub/CraftBook#1182]
<img width="1106" alt="Capture" src="https://user-images.githubusercontent.com/8324198/79048576-714dab00-7c1e-11ea-8bbf-dc0b333a6ada.PNG">

https://timings.aikar.co/?id=ddc7cef5cd814a04b0845b0951cfcabb

This server is running Paper version git-Paper-168 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
CraftBook version 3.10.2-SNAPSHOT;4569-b53bc8b
WorldEdit version 7.1.0-SNAPSHOT;4822-a27ade5

**Comment by me4502** [comment]
Please provide a profile such as /wg profile -p

Timings is ridiculously inaccurate for CraftBook and often blamed all redstone on it.

**Comment by andris155** [comment]
WG profile submit not work.
```
[15:29:19 INFO]: (Please wait... sending output to pastebin...)
[15:29:19 INFO]: Failed to submit paste: Unknown error. Please see console.
[15:29:19 ERROR]: Uncaught exception occurred in task: Submitting content to a pastebin service.
java.io.IOException: Did not get expected response code, got 413 for https://paste.enginehub.org/paste
at com.sk89q.worldedit.util.net.HttpRequest.expectResponseCode(HttpRequest.java:186) ~[?:?]
at com.sk89q.worldedit.util.paste.EngineHubPaste$PasteTask.call(EngineHubPaste.java:61) ~[?:?]
at com.sk89q.worldedit.util.paste.EngineHubPaste$PasteTask.call(EngineHubPaste.java:44) ~[?:?]
at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:139) ~[?:?]
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) ~[patched_1.15.2.jar:git-Paper-176]
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) ~[patched_1.15.2.jar:git-Paper-176]
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) ~[patched_1.15.2.jar:git-Paper-176]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by andris155** [comment]
[profile.txt](https://github.com/EngineHub/CraftBook/files/4469685/profile.txt)

**Comment by me4502** [comment]
It looks like pipes are barely taking any time at all. And the time pipes are taking is all in Spigot’s super slow Tile Entity handling. 

The biggest slowdown on your server appears to be world gen - did you not pregenerate your world?

**Comment by andris155** [comment]
Not pregenerated worlds. yes.
