### ISSUE TITLE
ICs 0110/0111 : some suddenly stopped working

### ISSUE THREAD

**Issue by Delawin** [EngineHub/CraftBook#1187]
Hi guys.

I don't know why but two of my wireless transmitters/receivers couples stopped working this afternoon. There's another one on the same chunk that is still working just fine.

I tried to recreate it but the issue is the same : once they're connected, and the transmitter is powered, the receiver turns on (sends power) but doesn't turn off when the transmitter isn't powered.

They're all self-triggered.

**Comment by me4502** [comment]
Can you provide your logs? And also provide a screenshot of the IC setup?

Generally, this is caused by a corrupt tile entity in the chunk, as the Spigot API only provides plugins with tile entities up until the corrupt one. So therefore any signs after that aren't told to plugins.

**Comment by Delawin** [comment]
Where can I get the logs you need ?
![2020-04-15_02 31 33](https://user-images.githubusercontent.com/63685684/79286759-e12f9000-7ec1-11ea-84d9-a9d76680fe41.png)
![2020-04-15_02 31 42](https://user-images.githubusercontent.com/63685684/79286768-e5f44400-7ec1-11ea-8cce-efd67e5aec38.png)

**Comment by me4502** [comment]
`logs/latest.log`

**Comment by Delawin** [comment]
[00:11:48] [Server thread/WARN]: [Essentials] Task #80156 for Essentials v2.17.2.0 generated an exception
java.lang.NullPointerException: null
	at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:150) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[00:40:21] [Server thread/WARN]: [Essentials] Task #87831 for Essentials v2.17.2.0 generated an exception
java.lang.NullPointerException: null
	at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:146) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[01:00:08] [Server thread/INFO]: Villager EntityVillager['Farmer'/433, uuid='1aae958f-4e42-42a3-ba0b-bc6b4006ce35', l='world', x=-4864.30, y=77.05, z=1804.30, cx=-305, cz=112, tl=6347181, v=true, d=false] died, message: 'Farmer was slain by Zombie'
[01:08:22] [Server thread/WARN]: [Essentials] Task #90797 for Essentials v2.17.2.0 generated an exception
java.lang.NullPointerException: null
	at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:142) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[01:20:17] [Craft Scheduler Thread - 1911/INFO]: [Vault] Checking for Updates ... 
[01:20:18] [Craft Scheduler Thread - 1911/INFO]: [Vault] No new version available
[02:04:30] [Server thread/WARN]: [Essentials] Task #91632 for Essentials v2.17.2.0 generated an exception
java.lang.NullPointerException: null
	at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:146) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[02:06:25] [Server thread/INFO]: Delawin issued server command: /creative
[02:06:47] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4914, z1908;[MC1111]S;PSPassageChambre
[02:07:44] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4914, z1908;[MC1111]S;PSPassageChambre
[02:16:10] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4912, z1911;[MC1110]S;000001
[02:16:27] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4914, z1908;[MC1111]S;000001
[02:17:33] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4914, z1908;[MC1111]S;000001
[02:20:56] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4912, z1911;[MC0110];000001
[02:21:12] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4914, z1908;[MC0111];000001
[02:27:29] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4914, z1908;[MC0111];PSPassageChambre
[02:27:52] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4914, z1908;[MC0111]S;Test123
[02:28:00] [Server thread/INFO]: This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[02:28:00] [Server thread/INFO]: Checking version, please wait...
[02:28:00] [Thread-61/INFO]: You are 40 version(s) behind
[02:28:07] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4914, z1908;[MC0111];Test123
[02:28:21] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4912, z1911;[MC0110];Test123
[02:30:58] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4912, z1911;[MC0110];Test123
[02:31:25] [Server thread/INFO]: [GriefPrevention] Delawin placed a sign @ world: x-4914, z1908;[MC0111];Test123

**Comment by me4502** [comment]
Can you provide the entire file at https://paste.enginehub.org and post the link here?

**Comment by me4502** [comment]
Also preferably join the discord at https://discord.gg/enginehub to discuss this

**Comment by Delawin** [comment]
https://paste.enginehub.org/CZS2RrDiD

**Comment by me4502** [comment]
That is not the entire file

**Comment by Delawin** [comment]
That is everything I have in latest.log

**Comment by Delawin** [comment]
Do you need the previous one ?

**Comment by me4502** [comment]
Then there is something else wrong with your server.

I can't really help much without the logs, but I'd recommend joining the Discord. From what you've provided this doesn't appear to be an issue with CraftBook, and this issue tracker is for bugs in CraftBook.

**Comment by Delawin** [comment]
I just joined the Discord.
The previous logs seems to provide more informations. Here it is, just in case.
https://paste.enginehub.org/MUDlgAOfW

**Comment by me4502** [comment]
Cool, are we able to move this conversation to the #craftbook channel on the Discord then?

**Comment by me4502** [comment]
Was found to be Spigot redstone connectivity regressions
