### ISSUE TITLE
Spigot 1.16.2 incompatible

### ISSUE THREAD

**Issue by Blueeyestar** [EngineHub/CraftBook#1218]
A new MC version is out now, 1.16.2, and so the fun starts all over again for all server owners. I hereby post the first mistake. Welcome to the sleepless nights :)

`[00:09:52] [Server thread/ERROR]: Could not load 'plugins\CraftBook_3.10.3-Build4641.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:381) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:186) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-379750e-9c9fb59]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.minecraft.util.commands.CommandPermissionsException
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-379750e-9c9fb59]
	... 7 more`

https://pastebin.com/LirpMyfC

**Comment by wizjany** [comment]
you're missing worldedit, that's not a 1.16.2 thing.

**Comment by Blueeyestar** [comment]
> 
> 
> you're missing worldedit, that's not a 1.16.2 thing.

it doesn't work with worldedit either. This is just a hint. I am aware that 1.16.2 is only new out :)

**Comment by me4502** [comment]
Can you provide an error with WorldEdit installed? The one you provides is entirely due to no WorldEdit.

**Comment by Blueeyestar** [comment]
https://pastebin.com/YQMGNR9z

**Comment by me4502** [comment]
That's a Spigot bug that has allegedly been fixed, update Spigot.

**Comment by Blueeyestar** [comment]
I updated it and it works fine now. Thanks for the hint :)
