### ISSUE TITLE
Gate sign NullPointerException error

### ISSUE THREAD

**Issue by andris155** [EngineHub/CraftBook#1244]
**Versions**

CraftBook version: 3.10.3;f1ee2df
Bukkit version: Purpur-993 (MC: 1.16.5)

**Describe the bug**

Gate sign cause console error sometimes.

**To Reproduce**

Use gate signs.

**Expected behavior**

Gate sign no cause console error.

**Additional context**

```
[14:16:29] [Server thread/ERROR]: Could not pass event SignChangeEvent to CraftBook v3.10.3;f1ee2df
java.lang.NullPointerException: null
	at com.sk89q.worldedit.world.block.FuzzyBlockState.equalsFuzzy(FuzzyBlockState.java:83) ~[?:?]
	at com.sk89q.worldedit.world.block.BaseBlock.equalsFuzzy(BaseBlock.java:210) ~[?:?]
	at com.sk89q.worldedit.blocks.Blocks.containsFuzzy(Blocks.java:48) ~[?:?]
	at com.sk89q.craftbook.mechanics.area.simple.Gate.isValidGateBlock(Gate.java:399) ~[?:?]
	at com.sk89q.craftbook.mechanics.area.simple.Gate.onSignChange(Gate.java:361) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1172.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-993]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-993]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-993]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2940) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$19(PlayerConnection.java:2888) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:350) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:364) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1212) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1205) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1181) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1025) ~[patched_1.16.5.jar:git-Purpur-993]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Purpur-993]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by me4502** [comment]
Can you please provide a screenshot of the sign? It seems for some reason it's an invalid block that's being seen as "null" rather than the normal default of stone

**Comment by gilbert0621** [comment]
Do you have a website or url

And I will log in

**Comment by me4502** [comment]
I don't understand the question sorry?
