### ISSUE TITLE
Area save error

### ISSUE THREAD

**Issue by korhox** [EngineHub/CraftBook#1247]
On command:
/area save test -n testnamespace
/area save test

In game result:
An error has occurred. See console:

In console:
`[17:22:25 INFO]: korho issued server command: /area save test
[17:22:25 WARN]: com.sk89q.minecraft.util.commands.WrappedCommandException: java.lang.NullPointerException
[17:22:25 WARN]: at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:534)
[17:22:25 WARN]: at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:514)
[17:22:25 WARN]: at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:469)
[17:22:25 WARN]: at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:407)
[17:22:25 WARN]: at com.sk89q.craftbook.bukkit.CraftBookPlugin.onCommand(CraftBookPlugin.java:768)
[17:22:25 WARN]: at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55)
[17:22:25 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:22:25 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2023)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1838)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1791)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[17:22:25 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[17:22:25 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[17:22:25 WARN]: Caused by: java.lang.NullPointerException
[17:22:25 WARN]: at com.sk89q.craftbook.mechanics.area.AreaCommands.saveArea(AreaCommands.java:66)
[17:22:25 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:22:25 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:22:25 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:22:25 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[17:22:25 WARN]: at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:526)
[17:22:25 WARN]: ... 24 more`

WorldEdit version: 7.2.3+5680-135941e
CraftBook version: 3.10.3;4680-f1ee2df
AsyncWorldEdit version: 3.8.2
Full logfile as attachment.
[ef2a7f.txt](https://github.com/EngineHub/CraftBook/files/6110339/ef2a7f.txt)

**Comment by me4502** [comment]
Try without AWE, forks of worldedit (especially AWE) are known to break the WorldEdit API, and therefore plugins using it.

**Comment by me4502** [comment]
Cannot be reproduced, and comments weren't addressed. Closing unless further information is provided leading to reproduction.
