### ISSUE TITLE
Little Issue on startup with Craftbook 3 and Spigot 1.17

### ISSUE THREAD

**Issue by CloudeLecaw** [EngineHub/CraftBook#1270]
i know your working on Craftbook 5.
But until this one is ready to use it would be nice to have a little compatiblity fix for Craftbook 3.
On startup we get the follow error

Might be just issues because of not 100% compatiblity of ProtcolLib and WorldEdit yet?

```
[10:33:15] [Server thread/INFO]: [CraftBook] Enabling CraftBook v3.10.4-SNAPSHOT;4700-609e3e4
[10:33:15] [Server thread/ERROR]: [CraftBook] You have a corrupt version of ProtocolLib! Please redownload it!
[10:33:15] [Server thread/ERROR]: [CraftBook] java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
	at com.sk89q.craftbook.util.compat.companion.CompanionPlugins.initiate(CompanionPlugins.java:52)
	at com.sk89q.craftbook.bukkit.CraftBookPlugin.onEnable(CraftBookPlugin.java:394)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 12 more

[10:33:15] [Server thread/INFO]: [CraftBook] Loading persistent data from YAML!
[10:33:15] [Server thread/ERROR]: [CraftBook] java.lang.IllegalStateException: Currently invalid
	at com.sk89q.worldedit.util.lifecycle.Lifecycled.lambda$valueOrThrow$0(Lifecycled.java:99)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.sk89q.worldedit.util.lifecycle.Lifecycled.valueOrThrow(Lifecycled.java:99)
	at com.sk89q.worldedit.bukkit.BukkitServerInterface.getWatchdog(BukkitServerInterface.java:128)
	at com.sk89q.worldedit.world.block.BlockState.generateStateMap(BlockState.java:120)
	at com.sk89q.worldedit.world.block.BlockType.lambda$new$3(BlockType.java:61)
	at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68)
	at com.sk89q.worldedit.world.block.BlockType.getBlockStatesMap(BlockType.java:91)
	at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:83)
	at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68)
	at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162)
	at com.sk89q.worldedit.world.block.BlockType.computeLegacy(BlockType.java:246)
	at com.sk89q.worldedit.world.block.BlockType.lambda$new$5(BlockType.java:66)
	at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68)
	at com.sk89q.worldedit.world.block.BlockType.getLegacyId(BlockType.java:228)
	at com.sk89q.craftbook.util.BlockSyntax.getBlock(BlockSyntax.java:75)
	at com.sk89q.craftbook.util.BlockSyntax.lambda$getBlocks$0(BlockSyntax.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.sk89q.craftbook.util.BlockSyntax.getBlocks(BlockSyntax.java:90)
	at com.sk89q.craftbook.mechanics.ic.gates.world.blocks.SetBlockAdmin$Factory.addConfiguration(SetBlockAdmin.java:119)
	at com.sk89q.craftbook.mechanics.ic.ICConfiguration.load(ICConfiguration.java:30)
	at com.sk89q.craftbook.mechanics.ic.ICManager.enable(ICManager.java:93)
	at com.sk89q.craftbook.mechanics.ic.ICMechanic.enable(ICMechanic.java:81)
	at com.sk89q.craftbook.bukkit.CraftBookPlugin.setupCraftBook(CraftBookPlugin.java:580)
	at com.sk89q.craftbook.bukkit.CraftBookPlugin.onEnable(CraftBookPlugin.java:451)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
	at java.base/java.lang.Thread.run(Thread.java:831)

[10:33:15] [Server thread/INFO]: [CraftBook] Enumerating chunks for self-triggered components...
[10:33:16] [Server thread/INFO]: [CraftBook] 1587 chunk(s) for 3 world(s) processed (205ms elapsed)
[10:33:16] [Server thread/WARN]: [CraftBook] ====================================================
[10:33:16] [Server thread/WARN]: [CraftBook]  CraftBook works better if you use Paper 
[10:33:16] [Server thread/WARN]: [CraftBook]  as your server software. 
[10:33:16] [Server thread/WARN]: [CraftBook] ===================================
```=================

**Comment by me4502** [comment]
Looks like you're missing protocollib or protocollib is failing to start. Not a CraftBook issue
