### ISSUE TITLE
Error at load in Spigot 1.18

### ISSUE THREAD

**Issue by alexchandel** [EngineHub/CraftBook#1283]
**Versions**

CraftBook version: 3.10.4
Bukkit version: CraftBukkit version 3335-Spigot-a5dea1c-a008701 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)

**Describe the bug**
The following error is printed at load:

```
[20:23:50] [Server thread/ERROR]: Could not load 'plugins/craftbook-3.10.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/craftbook/bukkit/bstats/charts/CustomChart
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:414) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3335-Spigot-a5dea1c-a008701]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3335-Spigot-a5dea1c-a008701]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:993) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3335-Spigot-a5dea1c-a008701]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3335-Spigot-a5dea1c-a008701]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/craftbook/bukkit/bstats/charts/CustomChart
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.craftbook.bukkit.bstats.charts.CustomChart
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	... 7 more
```

**To Reproduce**
1. Run CraftBook with Spigot 1.18

**Expected behavior**
Loads normally.

**Comment by me4502** [comment]
The jar on BukkitDev is corrupt - You can use this for now until they accept the update- https://ci.enginehub.org/repository/download/bt6/19066:id/craftbook-3.10.5-SNAPSHOT-dist.jar?branch=master&guest=1
