### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by AdminHcat** [EngineHub/CraftBook#1294]
**Versions**

CraftBook version: craftbook-bukkit-5.0.0-SNAPSHOT-dist
Bukkit version:  
server: purpur-1.18.1-1548.jar

**Describe the bug**

`$Applying patches
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (Eclipse OpenJ9 VM openj9-0.30.0) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
2022-02-08 07:15:11,944 ServerMain WARN Advanced terminal features are not available in this environment
[07:15:15 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[07:15:15 INFO]: Reloading ResourceManager: Default, bukkit
[07:15:15 INFO]: Loaded 7 recipes
[07:15:16 INFO]: Starting minecraft server version 1.18.1
[07:15:17 INFO]: Loading properties
[07:15:17 INFO]: This server is running Purpur version git-Purpur-1548 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 00ccf82 on HEAD)
[07:15:17 INFO]: Using 4 threads for Netty based IO
[07:15:17 INFO]: Server Ping Player Sample Count: 12
[07:15:17 INFO]: Default game type: SURVIVAL
[07:15:17 INFO]: Generating keypair
[07:15:17 INFO]: Starting Minecraft server on *:25565
[07:15:17 INFO]: Using default channel type
[07:15:17 INFO]: Paper: Using Java 11 compression from Velocity.
[07:15:17 INFO]: Paper: Using Java cipher from Velocity.
[07:15:19 ERROR]: Could not load 'plugins\craftbook-bukkit-5.0.0-SNAPSHOT-dist.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com.sk89q.worldedit.util.auth.AuthorizationException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:422) ~[purpur-1.18.1.jar:git-Purpur-1548]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1548]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.18.1.jar:git-Purpur-1548]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1548]
        at net.minecraft.server.MinecraftServer$$Lambda$3976/0x000000007db0ca20.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:884) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com.sk89q.worldedit.util.auth.AuthorizationException
        at java.lang.Class.forNameImpl(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:427) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.util.auth.AuthorizationException
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:1112) ~[?:?]
        at java.lang.Class.forNameImpl(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:427) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 8 more`

**To Reproduce**

load  plugin

**Expected behavior**
Unable to load plugin

**Screenshots**

**Additional context**

**Comment by me4502** [comment]
Looks like you're missing worldedit but can't 100% say given it's not the entire logs.

Use the discord for support

**Comment by AdminHcat** [comment]
> Looks like you're missing worldedit but can't 100% say given it's not the entire logs.
> 
> Use the discord for support

i use FastAsyncWorldEdit-Bukkit-2.0.2 Does it support

**Comment by me4502** [comment]
That's entirely up to whether they break the worldedit API or not, but as I said - use discord for support
