### ISSUE TITLE
hello，My English is very poor, I am a user from China, I encountered the following problems in the process of using the plugin

### ISSUE THREAD

**Issue by Wmh125364** [EngineHub/CraftBook#1324]
### CraftBook Version

3.10.6

### Platform Version

paper.1.18.2-build388.jar

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Always output the following error in my cmd terminal:
[22:49:18 WARN]: [CraftBook] Task #5511 for CraftBook v3.10.6;4748-a91298e generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "this.this$0.chairs" is null
        at com.sk89q.craftbook.mechanics.Chair$ChairChecker.run(Chair.java:289) ~[craftbook-3.10.6 (1).jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behavior

I hope to find a solution

### Reproduction Steps

1. ...
2. ...

**Comment by me4502** [comment]
Most of the error is missing, so there's nothing I can say based on it. You're also using a very outdated version
