### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by CloudeLecaw** [EngineHub/CraftBook#1331]
### CraftBook Version

CraftBook_3.10.12-Build4862

### Platform Version

1.21.1-15-master@11b4ac7

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

the error apeared in console multiple times like a Spam
we dont know why

### Expected Behavior

no Spam 

### Reproduction Steps

if we would know we could descrioe steps

### Anything Else?

error code

```
[14:33:26] [Server thread/ERROR]: Could not pass event SourcedBlockRedstoneEvent to CraftBook v3.10.12-SNAPSHOT;4862-4e65553
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Enchantment cannot be null
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4012) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5020) ~[guava-32.1.2-jre.jar:?]
	at CraftBook_3.10.12-Build4862.jar/com.sk89q.craftbook.util.ItemSyntax.getItem(ItemSyntax.java:300) ~[CraftBook_3.10.12-Build4862.jar:?]
	at CraftBook_3.10.12-Build4862.jar/com.sk89q.craftbook.mechanics.pipe.Pipes.searchNearbyPipes(Pipes.java:148) ~[CraftBook_3.10.12-Build4862.jar:?]
	at CraftBook_3.10.12-Build4862.jar/com.sk89q.craftbook.mechanics.pipe.Pipes.startPipe(Pipes.java:376) ~[CraftBook_3.10.12-Build4862.jar:?]
	at CraftBook_3.10.12-Build4862.jar/com.sk89q.craftbook.mechanics.pipe.Pipes.onBlockRedstoneChange(Pipes.java:481) ~[CraftBook_3.10.12-Build4862.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1070.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at CraftBook_3.10.12-Build4862.jar/com.sk89q.craftbook.bukkit.MechanicListenerAdapter.handleDirectWireInput(MechanicListenerAdapter.java:345) ~[CraftBook_3.10.12-Build4862.jar:?]
	at CraftBook_3.10.12-Build4862.jar/com.sk89q.craftbook.bukkit.MechanicListenerAdapter.handleRedstoneForBlock(MechanicListenerAdapter.java:263) ~[CraftBook_3.10.12-Build4862.jar:?]
	at CraftBook_3.10.12-Build4862.jar/com.sk89q.craftbook.bukkit.MechanicListenerAdapter.onBlockRedstoneChange(MechanicListenerAdapter.java:184) ~[CraftBook_3.10.12-Build4862.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.RedStoneWireBlock.updatePowerStrength(RedStoneWireBlock.java:378) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.RedStoneWireBlock.updateSurroundingRedstone(RedStoneWireBlock.java:275) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.RedStoneWireBlock.neighborChanged(RedStoneWireBlock.java:543) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.handleNeighborChanged(BlockBehaviour.java:1174) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.redstone.NeighborUpdater.executeUpdate(NeighborUpdater.java:66) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.runNext(CollectingNeighborUpdater.java:130) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.runUpdates(CollectingNeighborUpdater.java:80) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.addAndRun(CollectingNeighborUpdater.java:65) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.neighborChanged(CollectingNeighborUpdater.java:37) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.level.ServerLevel.neighborChanged(ServerLevel.java:1753) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.DiodeBlock.updateNeighborsInFront(DiodeBlock.java:198) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.DiodeBlock.onPlace(DiodeBlock.java:183) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.state.BlockBehaviour.onPlace(BlockBehaviour.java:164) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onPlace(BlockBehaviour.java:1209) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onPlace(BlockBehaviour.java:1205) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:406) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.Level.setBlock(Level.java:1051) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.Level.setBlock(Level.java:1012) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.DiodeBlock.tick(DiodeBlock.java:72) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1222) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1192) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:192) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:89) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Enchantment cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.inventory.CraftItemStack.addUnsafeEnchantment(CraftItemStack.java:256) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at CraftBook_3.10.12-Build4862.jar/com.sk89q.craftbook.util.ItemSyntax$1.load(ItemSyntax.java:215) ~[CraftBook_3.10.12-Build4862.jar:?]
	at CraftBook_3.10.12-Build4862.jar/com.sk89q.craftbook.util.ItemSyntax$1.load(ItemSyntax.java:143) ~[CraftBook_3.10.12-Build4862.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080) ~[guava-32.1.2-jre.jar:?]
	... 54 more
```

**Comment by me4502** [comment]
Do you have some plugin adding custom enchantments? It looks like something within the Bukkit API itself is failing with a broken enchantment, there’s not much I can do without more information on actually reproducing this. It could be a Paper bug or a bug in another plugin, but I’d need more information on how to actually reproduce it.

**Comment by CloudeLecaw** [comment]
Ehm no.. we use no custom enchantments.
just normal enchant table
Well The server often runs without an issue 1-2 days
and then this error comes and spamed arround 3-4 mb log
