### ISSUE TITLE
Lift signs triggered by pressure plates crash client.

### ISSUE THREAD

**Issue by andrewkm** [EngineHub/CraftBook#1338]
### CraftBook Version

CraftBook5 v5.0.0-SNAPSHOT+4871-5522e6f

### Platform Version

Paper 1.21.3-63-master@4190ee7

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using a version of CraftBook compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Step on a pressure plate that activates a lift sign.
Crash.

Connection Lost; Internal server error:
https://i.imgur.com/8PXtQvT.png

Error in console:
```
[17:39:12] [Server thread/WARN]: Failed to handle packet for /redactedip:redactedport
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:1145) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:356) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.network.Connection.tick(Connection.java:638) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:248) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.server.MinecraftServer.tickConnection(MinecraftServer.java:1917) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.server.dedicated.DedicatedServer.tickConnection(DedicatedServer.java:453) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1890) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1664) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1329) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096) ~[?:?]
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050) ~[?:?]
	at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1774) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1399) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1386) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3659) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:598) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3306) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.world.entity.player.Player.tick(Player.java:288) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:1063) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	... 10 more
```

### Expected Behavior

Not crash.

### Reproduction Steps

https://www.youtube.com/watch?v=Cn6lqpJkfrQ

**Comment by me4502** [comment]
from investigating, this appears to be a bug in Paper currently

**Comment by andrewkm** [comment]
This has now been fixed.
